apps:
- name: scrambler
  script: www
  out_file: /dev/null
  error_file: /dev/null
  cwd: D:\nodeproject\stickearn-api\scrambler\bin
  env:
    SESSION_KEY : RE~GRWEYAT^*
    SESSION_STORAGE : S_ID
    PORT : 6001
    SALT : 10
    API_URL : http://localhost:8080/api/
    UV_THREADPOOL_SIZE: 12
    REDIS_CON: localhost:6379
    MONGO_URL: mongodb://localhost:27017/userapp
    NODE_ENV: development